### ISSUE TITLE
ElasticSearch cluster fails to start on Azure

### ISSUE THREAD

**Issue by mario-paniccia** [elastic/azure-marketplace#214]
I've deployed an ElasticSearch 6.3.0 cluster on Azure. But the cluster is failing to start. Checking the data nodes logs I see the following:

`[2018-07-25T00:00:01,963][WARN ][o.e.d.z.UnicastZenPing   ] [data-0] failed to resolve host [master-2:9300]
java.net.UnknownHostException: master-2: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_181]
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_181]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_181]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:1.8.0_181]
        at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_181]
        at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_181]
        at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:933) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:888) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:702) ~[elasticsearch-6.3.0.jar:6.3.0]
        at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$resolveHostsLists$0(UnicastZenPing.java:212) ~[elasticsearch-6.3.0.jar:6.3.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:625) [elasticsearch-6.3.0.jar:6.3.0]`

The config file on the master is as follow:
```node.name: "master-0"
path.logs: /var/log/elasticsearch
path.data: /var/lib/elasticsearch
discovery.zen.ping.unicast.hosts: ["master-0:9300","master-1:9300","master-2:9300"]
node.master: true
node.data: false
discovery.zen.minimum_master_nodes: 2
network.host: [_site_, _local_]
node.max_local_storage_nodes: 1
bootstrap.memory_lock: true

**Comment by russcam** [comment]
Do you have your own DNS configured for the VNet to which the cluster is attached? The template assumes that Azure DNS is used, which is able to resolve IP local addresses from hostnames.

**Comment by mario-paniccia** [comment]
you are correct @russcam. We use custom DNS for the VNet. Any way I can fix this issue operating on the ARM template parameters?

**Comment by russcam** [comment]
It's possible to configure your own DNS servers to resolve hostnames correctly, by forwarding DNS queries to Azure to resolve

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances#name-resolution-using-your-own-dns-server

Custom DNS configuration is beyond the feature scope of the template, since it can be so environment specific.

**Comment by mario-paniccia** [comment]
We already have forwarders in place in the vnet, the custom dns 168.63.129.16. But still not able to resolve the host

![image](https://user-images.githubusercontent.com/9882391/43257467-c8d1c71a-90c7-11e8-854d-466879426f3c.png)

**Comment by mario-paniccia** [comment]
still issues. I've deployed on a separate VNet. The cluster fails to start, on the master I see: 

```java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
	at org.elasticsearch.common.network.NetworkUtils.getSiteLocalAddresses(NetworkUtils.java:184) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:213) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:187) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:106) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:758) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:135) ~[?:?]
	at org.elasticsearch.xpack.core.security.transport.netty4.SecurityNetty4Transport.doStart(SecurityNetty4Transport.java:85) ~[?:?]
	at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4ServerTransport.doStart(SecurityNetty4ServerTransport.java:41) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:66) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:213) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:66) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.node.Node.start(Node.java:652) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:265) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:335) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.3.0.jar:6.3.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) [elasticsearch-6.3.0.jar:6.3.0]

**Comment by russcam** [comment]
@mario-paniccia please could you supply the parameters you're using, and the command(s) to deploy?

**Comment by mario-paniccia** [comment]
the deploy is done by our build pipeline. I supplied a elk terraform module with the following parameters:
```
parameters = {
    # See https://github.com/elastic/azure-marketplace#parameters
    artifactsBaseUrl  = "https://raw.githubusercontent.com/elastic/azure-marketplace/6.3.0/src"
    esClusterName     = "${var.product}-elastic-search-${var.env}"
    location          = "${azurerm_resource_group.elastic-resourcegroup.location}"

    esVersion         = "6.3.0"
    xpackPlugins      = "No"
    kibana            = "Yes"

    adminUsername     = "elkadmin"
    adminPassword     = "aaaa678_"
    securityAdminPassword = "aaaa678_"
    securityKibanaPassword = "aaaa678_"
    securityBootstrapPassword = ""
    securityLogstashPassword = "aaaa678_"
    securityReadPassword = "aaaa678_"

    vNetNewOrExisting = "new"
    vNetName          = "elastic-search-sandbox-vnet"
    vNetNewAddressPrefix = "40.0.0.0/24"
    vNetLoadBalancerIp = "40.0.0.4"
    vNetNewClusterSubnetAddressPrefix = "40.0.0.0/25"

    vmSizeKibana = "Standard_A2"
    vmSizeDataNodes = "Standard_A2"
    vmSizeClientNodes = "Standard_A2"
    vmSizeMasterNodes = "Standard_A2"
  }

**Comment by russcam** [comment]
Which mainTemplate.json does it target? It would be something similar to `artifactsBaseUrl`, but with mainTemplat.json appended

**Comment by mario-paniccia** [comment]
it targets `mainTemplate.json`
In a previous build I was using the default settings for the `vNetNewAddressPrefix`, `vNetLoadBalancerIp` and `vNetNewClusterSubnetAddressPrefix`. The cluster started. 
After I added parameters to override the default ip address range for the VNet, I'm getting the issue

**Comment by mario-paniccia** [comment]
@russcam I've fixed the issue. I did use a wrong ip range for the vnet. Changing that to a free address range sorted the issue. The cluster is starting now 👍

**Comment by russcam** [comment]
Glad you got it sorted @mario-paniccia!
