### ISSUE TITLE
Azure Disk Encryption

### ISSUE THREAD

**Issue by robertmarks** [elastic/azure-marketplace#251]
We have a requirement to enable Azure Disk Encryption for both OS and Data disks. Currently when attempting to enable this we are getting an error.

This is the first error that is seen - this is attempt #5 of 10.
```
OsVolumeEncrypted          : EncryptionInProgress
DataVolumesEncrypted       : EncryptionInProgress
OsVolumeEncryptionSettings : Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings
ProgressMessage            : Attempt #5 to unmount /oldroot failed with error: Command umount /oldroot failed with return code 32
                             stdout:
                             
                             stderr:
                             umount: /oldroot: target is busy
                                     (In some cases useful info about processes that
                                      use the device is found by lsof(8) or fuser(1).)
                             , stack trace: Traceback (most recent call last):
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py", line 170, in start_encryption
                                 self.retry_unmount_oldroot()
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/transitions/transitions/core.py", line 222, in trigger
                                 return self.machine.process(f)
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/transitions/transitions/core.py", line 526, in process
                                 return trigger()
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/transitions/transitions/core.py", line 247, in _trigger
                                 if t.execute(event):
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/transitions/transitions/core.py", line 145, in execute
                                 machine.callback(func, event_data)
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/transitions/transitions/core.py", line 518, in callback
                                 func(*event_data.args, **event_data.kwargs)
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py", line 114, in on_enter_state
                                 super(Ubuntu1604EncryptionStateMachine, self).on_enter_state()
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/main/oscrypto/OSEncryptionStateMachine.py", line 65, in on_enter_state
                                 self.state_objs[self.state].enter()
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/main/oscrypto/ubuntu_1604/encryptstates/UnmountOldrootState.py", line 130, in enter
                                 self.command_executor.Execute('umount /oldroot', True)
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/main/CommandExecutor.py", line 73, in Execute
                                 raise Exception(msg)
                             Exception: Command umount /oldroot failed with return code 32
                             stdout:
                             
                             stderr:
                             umount: /oldroot: target is busy
                                     (In some cases useful info about processes that
                                      use the device is found by lsof(8) or fuser(1).)
```

Final error is:
```
OsVolumeEncrypted          : EncryptionInProgress
DataVolumesEncrypted       : EncryptionInProgress
OsVolumeEncryptionSettings : Microsoft.Azure.Management.Compute.Models.DiskEncryptionSettings
ProgressMessage            : Failed to encrypt OS volume with error: Attempt #11 to unmount /oldroot failed with error: Could not unmount /oldroot in 10 attempts, stack trace: Traceback (most recent call last):
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py", line 168, in start_encryption
                                 raise Exception("Could not unmount /oldroot in 10 attempts")
                             Exception: Could not unmount /oldroot in 10 attempts
                             , stack trace: Traceback (most recent call last):
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/main/handle.py", line 1613, in daemon_encrypt
                                 os_encryption.start_encryption()
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py", line 185, in start_encryption
                                 raise Exception(message)
                             Exception: Attempt #11 to unmount /oldroot failed with error: Could not unmount /oldroot in 10 attempts, stack trace: Traceback (most recent call last):
                               File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999326/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py", line 168, in start_encryption
                                 raise Exception("Could not unmount /oldroot in 10 attempts")
                             Exception: Could not unmount /oldroot in 10 attempts
                             
                             , machine state: unmount_oldroot
```

Is the use of ADE achievable for an elastic cluster deployed using Azure CLI 2.0?

**Comment by darrell-tethr** [comment]
I had the exact same problem.  For me, the fix was to stop the ES JVM process before running the encryption command.  The encryption process needs plenty of RAM to complete.

**Comment by robertmarks** [comment]
@darrell-tethr found that just stopping the ES service wasn't enough, it still gave the above errors about `unmount_oldroot`. 

In the end I stopped the service, disabled it, rebooted the vm prior to encyption and then ran the same command for encryption this gave a successful encrypt.

Obviously this was all tested on a test instance (single master/data).

Now to do this for an entire 9 box cluster...

**Comment by darrell-tethr** [comment]
@robertmarks I've been meaning to test restoring an ES cluster but I haven't gotten tried yet. Thanks for the warning.  If you find a fix, please let me know. Thanks!

**Comment by robertmarks** [comment]
@darrell-tethr Found that post restore, the OS disk will come back just fine. For the datadisk which is mounted at `/datadisks/disk1` you need to run the `Set-AzureRmVmDiskEncryptionExtension -VolumeType Data` or `az vm encryption enable --volume-type data` command (obviously needs the full command). 

More detail [here](https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-automation#create-a-vm-from-restored-disks) - Step 4
