### ISSUE TITLE
Not able to log in to kibana dashboard and getting error 

### ISSUE THREAD

**Issue by asraful** [elastic/azure-marketplace#339]
I am launched ELK from azure marketplace provided by elastic .
Deployment was ok . 
In time of deployment of the stack , i did not get any option to set kibana dashboard user password . The password i set for all default users are used in internal VM .

My Question : 
What is the default user/pass here for kibana front end.

Apart from that :  I am getting bellow error in kibana VM .

`
{"type":"log","@timestamp":"2020-05-09T08:29:06Z","tags":["listening","info"],"pid":3029,"message":"Server running at http://10.1.7.9:5601"}
{"type":"log","@timestamp":"2020-05-09T08:29:06Z","tags":["reporting","error"],"pid":3029,"message":"The Reporting plugin encountered issues launching Chromium in a self-test. You may have trouble generating reports."}
{"type":"error","@timestamp":"2020-05-09T08:29:06Z","tags":["reporting","error"],"pid":3029,"level":"error","error":{"message":"Failed to launch chrome!\n/var/lib/kibana/headless_shell-linux/headless_shell: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n","name":"Error","stack":"Error: Failed to launch chrome!\n/var/lib/kibana/headless_shell-linux/headless_shell: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\n    at onClose (/usr/share/kibana/node_modules/puppeteer-core/lib/Launcher.js:349:14)\n    at Interface.helper.addEventListener (/usr/share/kibana/node_modules/puppeteer-core/lib/Launcher.js:338:50)\n    at Interface.emit (events.js:194:15)\n    at Interface.close (readline.js:379:8)\n    at Socket.onend (readline.js:157:10)\n    at Socket.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"message":"Failed to launch chrome!\n/var/lib/kibana/headless_shell-linux/headless_shell: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"}
`

Any help on this ?

**Comment by asraful** [comment]
Issue is fixed :
able to log in with user : elastic  

seems, this needed to be written somewhere in the document  that this same user works for kibana dashboard also .
